local TriangleShooterLevels = {}

local levels = {
    [1] = {
        timeLimitSeconds = 15,
        enemyCount = 1,
        enemyHealth = 35,
        enemyProjectiles = false,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1000,
        windowHeight = 600,
    },
    [2] = {
        timeLimitSeconds = 20,
        enemyCount = 1,
        enemyHealth = 50,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.5,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1026,
        windowHeight = 640,  
    },
    [3] = {
        timeLimitSeconds = 20,
        enemyCount = 2,
        enemyHealth = 40,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.75,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 960,
        windowHeight = 460,
    },
    [4] = {
        timeLimitSeconds = 15,
        enemyCount = 1,
        enemyHealth = 80,
        enemyProjectiles = true,
        wallPingPong = true,
        enemyShootIntervalSeconds = 0.1,
        coinPerHit = 1,
        windowWidth = 600,
        windowHeight = 400,
    },
    [5] = {
        timeLimitSeconds = 20,
        enemyCount = 3,
        enemyHealth = 40,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.5,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1026,
        windowHeight = 640,
    },
    [6] = {
        timeLimitSeconds = 15,
        enemyCount = 2,
        enemyHealth = 60,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.5,
        wallPingPong = true,
        coinPerHit = 1,
        windowWidth = 1026,
        windowHeight = 640,
    },
    [7] = {
        timeLimitSeconds = 15,
        enemyCount = 3,
        enemyHealth = 60,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.35,
        wallPingPong = true,
        coinPerHit = 1,
        windowWidth = 900,
        windowHeight = 400,
    },
    [8] = {
        timeLimitSeconds = 20,
        enemyCount = 1,
        enemyHealth = 200,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.15,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 700,
        windowHeight = 400,
    },
    [9] = {
        timeLimitSeconds = 15,
        enemyCount = 5,
        enemyHealth = 45,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.35,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1026,
        windowHeight = 640,
    },
    
}

function TriangleShooterLevels.getLevelConfig(index)
    return levels[index]
end

return TriangleShooterLevels
