local TriangleShooterLevels = {}

local levels = {
    [1] = {
        timeLimitSeconds = 15,
        enemyCount = 1,
        enemyHealth = 30,
        enemyProjectiles = false,
        enemyShootIntervalSeconds = 0.5,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1026,
        windowHeight = 640,
    },
    [2] = {
        timeLimitSeconds = 20,
        enemyCount = 1,
        enemyHealth = 50,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.5,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1026,
        windowHeight = 400,
    },
    [3] = {
        timeLimitSeconds = 20,
        enemyCount = 2,
        enemyHealth = 40,
        enemyProjectiles = true,
        enemyShootIntervalSeconds = 0.75,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 960,
        windowHeight = 460,
    },
    [4] = {
        timeLimitSeconds = 15,
        enemyCount = 1,
        enemyHealth = 80,
        enemyProjectiles = true,
        wallPingPong = false,
        enemyShootIntervalSeconds = 0.1,
        coinPerHit = 1,
        windowWidth = 600,
        windowHeight = 400,
    },
    [5] = {
        timeLimitSeconds = 15,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1000,
        windowHeight = 600,
        enemies = {
            { movementType = "stationary", x = 500, y = 300, health = 105, shootPattern = "cone", projectileCount = 4, shootInterval = 0.3 },
        },
    },
    [6] = {
        timeLimitSeconds = 20,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1026,
        windowHeight = 640,
        enemies = {
            { movementType = "bounce", health = 40, shootInterval = 0.5 },
            { movementType = "stationary", x = 513, y = 320, health = 50, shootPattern = "cone", projectileCount = 3, shootInterval = 0.8 },
        },
    },
    [7] = {
        timeLimitSeconds = 20,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1000,
        windowHeight = 600,
        enemies = {
            { movementType = "orbit", orbitCenter = {500, 300}, orbitRadius = 120, orbitSpeed = 1.2, health = 50, color = {100, 150, 255}, shootInterval = 0.6 },
            { movementType = "orbit", orbitCenter = {500, 300}, orbitRadius = 120, orbitSpeed = -1.2, health = 50, color = {100, 150, 255}, shootInterval = 0.6 },
            { movementType = "orbit", orbitCenter = {500, 300}, orbitRadius = 120, orbitSpeed = -1.2, health = 50, color = {100, 150, 255}, shootInterval = 0.6 },
            { movementType = "bounce", health = 40, shootInterval = 0.5 },

        },
    },
    [8] = {
        timeLimitSeconds = 15,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 800,
        windowHeight = 500,
        enemies = {
            { movementType = "bounce", health = 60, speed = 1.3, shootInterval = 0.4 },
            { movementType = "bounce", health = 60, speed = 1.3, shootInterval = 0.4 },
        },
    },
    [9] = {
        timeLimitSeconds = 15,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1100,
        windowHeight = 650,
        enemies = {
            { movementType = "stationary", x = 550, y = 325, health = 200, size = 64, color = {255, 100, 100}, shootPattern = "circle", projectileCount = 6, shootInterval = 0.3, spinWhileShooting = true },
        },
    },
    [10] = {
        timeLimitSeconds = 20,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1100,
        windowHeight = 650,
        enemies = {
            { movementType = "stationary", x = 550, y = 325, health = 100, shootPattern = "cone", projectileCount = 3, shootInterval = 0.7 },
            { movementType = "orbit", orbitCenter = {550, 325}, orbitRadius = 150, orbitSpeed = 1.0, health = 65, color = {100, 255, 150}, shootInterval = 0.8 },
            { movementType = "orbit", orbitCenter = {550, 325}, orbitRadius = 150, orbitSpeed = -1.0, health = 65, color = {100, 255, 150}, shootInterval = 0.8 },
        },
    },
    [11] = {
        timeLimitSeconds = 20,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 900,
        windowHeight = 500,
        enemies = {
            { movementType = "bounce", health = 50, speed = 1.2, shootPattern = "cone", projectileCount = 2, shootInterval = 0.5 },
            { movementType = "bounce", health = 50, speed = 1.2, shootPattern = "cone", projectileCount = 2, shootInterval = 0.5 },
            { movementType = "bounce", health = 50, speed = 1.2, shootPattern = "cone", projectileCount = 2, shootInterval = 0.5 },
        },
    },
    [12] = {
        timeLimitSeconds = 15,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1200,
        windowHeight = 700,
        enemies = {
            { movementType = "orbit", orbitCenter = {600, 350}, orbitRadius = 100, orbitSpeed = 1.5, health = 60, shootPattern = "circle", projectileCount = 5, shootInterval = 1.2, spinWhileShooting = true },
            { movementType = "orbit", orbitCenter = {600, 350}, orbitRadius = 100, orbitSpeed = -1.5, health = 60, shootPattern = "circle", projectileCount = 5, shootInterval = 1.2, spinWhileShooting = true },
            { movementType = "bounce", health = 50, shootInterval = 0.6 },
            { movementType = "bounce", health = 50, shootInterval = 0.6 },
        },
    },
    [13] = {
        timeLimitSeconds = 20,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1000,
        windowHeight = 600,
        enemies = {
            { movementType = "stationary", x = 300, y = 300, health = 70, shootPattern = "cone", projectileCount = 3, shootInterval = 0.6 },
            { movementType = "stationary", x = 700, y = 300, health = 70, shootPattern = "cone", projectileCount = 3, shootInterval = 0.6 },
            { movementType = "bounce", health = 60, speed = 1.4, shootInterval = 0.4 },
        },
    },
    [14] = {
        timeLimitSeconds = 20,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 900,
        windowHeight = 550,
        enemies = {
            { movementType = "stationary", x = 450, y = 275, health = 200, size = 72, color = {255, 80, 80}, shootPattern = "circle", projectileCount = 8, shootInterval = 0.8, spinWhileShooting = true },
            { movementType = "orbit", orbitCenter = {450, 275}, orbitRadius = 160, orbitSpeed = 0.9, health = 60, color = {80, 180, 255}, shootInterval = 0.7 },
            { movementType = "orbit", orbitCenter = {450, 275}, orbitRadius = 160, orbitSpeed = -0.9, health = 60, color = {80, 180, 255}, shootInterval = 0.7 },
            { movementType = "orbit", orbitCenter = {450, 275}, orbitRadius = 160, orbitSpeed = -0.9, health = 60, color = {80, 180, 255}, shootInterval = 0.7 },
        },
    },
    [15] = {
        timeLimitSeconds = 30,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1300,
        windowHeight = 750,
        enemies = {
            { movementType = "stationary", x = 650, y = 375, health = 200, size = 80, color = {255, 50, 50}, shootPattern = "circle", projectileCount = 10, shootInterval = 0.5, spinWhileShooting = true },
            { movementType = "orbit", orbitCenter = {650, 375}, orbitRadius = 200, orbitSpeed = 0.8, health = 60, color = {50, 200, 255}, shootPattern = "cone", projectileCount = 2, shootInterval = 0.8 },
            { movementType = "orbit", orbitCenter = {650, 375}, orbitRadius = 200, orbitSpeed = -0.8, health = 60, color = {50, 200, 255}, shootPattern = "cone", projectileCount = 2, shootInterval = 0.8 },
            { movementType = "bounce", health = 50, speed = 1.3, color = {150, 255, 100}, shootInterval = 0.5 },
        },
    },
    [16] = {
        timeLimitSeconds = 30,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1100,
        windowHeight = 700,
        enemies = {
            { movementType = "teleporter", x = 550, y = 350, health = 300, size = 40, teleportChargeTime = 0.85, beamDuration = 0.3, teleportCooldown = 1.5 },
        },
    },
    [17] = {
        timeLimitSeconds = 35,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1200,
        windowHeight = 700,
        enemies = {
            { movementType = "teleporter", x = 600, y = 350, health = 250, size = 40, teleportChargeTime = 0.95, beamDuration = 0.25, teleportCooldown = 1.8 },
            { movementType = "orbit", orbitCenter = {600, 350}, orbitRadius = 180, orbitSpeed = 1.0, health = 50, shootInterval = 0.7 },
            { movementType = "orbit", orbitCenter = {600, 350}, orbitRadius = 180, orbitSpeed = -1.0, health = 50, shootInterval = 0.7 },
        },
    },
    [18] = {
        timeLimitSeconds = 40,
        enemyProjectiles = true,
        wallPingPong = false,
        coinPerHit = 1,
        windowWidth = 1400,
        windowHeight = 800,
        enemies = {
            { movementType = "teleporter", x = 400, y = 400, health = 200, size = 40, teleportChargeTime = 0.75, beamDuration = 0.35, teleportCooldown = 1.2 },
            { movementType = "bounce", health = 60, speed = 1.2, shootPattern = "cone", projectileCount = 2, shootInterval = 0.5 },
            { movementType = "bounce", health = 60, speed = 1.2, shootPattern = "cone", projectileCount = 2, shootInterval = 0.5 },
            { movementType = "bounce", health = 60, speed = 1.2, shootPattern = "cone", projectileCount = 2, shootInterval = 0.5 },
            { movementType = "orbit", orbitCenter = {600, 350}, orbitRadius = 180, orbitSpeed = -1.0, health = 50, shootInterval = 0.7 },
        },
    },
}

function TriangleShooterLevels.getLevelConfig(index)
    return levels[index]
end

return TriangleShooterLevels
